
server:
  port: '8003'

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/movies
    password: mysql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
